apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/fluxcd/flux2//manifests/integrations/registry-credentials-sync/azure?ref=main
# - git@github.com/fluxcd/flux2//manifests/integrations/registry-credentials-sync/azure
# patchesStrategicMerge:
# - config-patches.yaml